version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: barbery-database
    restart: always
    environment:
      POSTGRES_DB: barbery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: barbery-pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin@postgres.com
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
